@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2Fb61fa675b87f1b99e9f3af83b37ad30e9a5e8c59%5C%2Fplantuml%5C%2FMSA%5C%2Fdatabase-patterns%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/b61fa675b87f1b99e9f3af83b37ad30e9a5e8c59/plantuml/MSA/database-patterns.puml https://gitlab.com/nghinhut/docs/blob/b61fa675b87f1b99e9f3af83b37ad30e9a5e8c59/plantuml/MSA/database-patterns.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----

rectangle "Database Patterns" as Database #green

rectangle "Database per Service" as DatabaseP1
rectangle "Shared Database per Service" as DatabaseP2
rectangle "Command Query Responsibility Segregation (CQRS)" as DatabaseP3
rectangle "Event Sourcing" as DatabaseP4
rectangle "Saga Pattern" as DatabaseP5
Database --- DatabaseP1
Database --- DatabaseP2
Database --- DatabaseP3
Database --- DatabaseP4
Database --- DatabaseP5
@enduml