@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F9272fa80c3a85392ddde1b399e46920388b3f8d2%5C%2Fplantuml%5C%2FMSA%5C%2Fmsa-goals%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/9272fa80c3a85392ddde1b399e46920388b3f8d2/plantuml/MSA/msa-goals.puml https://gitlab.com/nghinhut/docs/blob/9272fa80c3a85392ddde1b399e46920388b3f8d2/plantuml/MSA/msa-goals.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title The Microservices Goals

rectangle "Microservices Architecture" as msa #green

rectangle "Reduce Cost" as goal1 #yellow
rectangle "Increase Release Speed" as goal2 #yellow
rectangle "Improve Resilience" as goal3 #yellow
rectangle "Enable Visibility" as goal4 #yellow

msa -- goal1
msa -- goal2
msa -- goal3
msa -- goal4

@enduml