@startuml
title Design Patterns for Microservices

!if (%file_exists("../shared/functions.iuml"))
    !include ../shared/functions.iuml
!else
    !include https://gitlab.com/nghinhut/docs/raw/master/plantuml/shared/functions.iuml
!endif

rectangle "Design Patterns for [[$getBaseUrl()/plantuml/msa.puml Microservices]]" as DpfMSA #yellow

rectangle "[[$getBaseUrl()/plantuml/MSA/decomposition-patterns.puml Decomposition Patterns]]" as Decomposition #green
rectangle "[[$getBaseUrl()/plantuml/MSA/integration-patterns.puml Integration Patterns]]" as Integration #green
rectangle "[[$getBaseUrl()/plantuml/MSA/database-patterns.puml Database Patterns]]" as Database #green
rectangle "[[$getBaseUrl()/plantuml/MSA/observability-patterns.puml Observability Patterns]]" as Observability #green
rectangle "[[$getBaseUrl()/plantuml/MSA/cross-cutting-concern-patterns.puml Cross-Cutting Concern Patterns]]" as CrossCuttingConcern #green
DpfMSA --- Decomposition
DpfMSA --- Integration
DpfMSA --- Database
DpfMSA --- Observability
DpfMSA --- CrossCuttingConcern
@enduml
