@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F8e9f9814d34554d4cd92a08dec3b80074ca83cf2%5C%2Fplantuml%5C%2FMSA%5C%2Fmsa-design-patterns%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/8e9f9814d34554d4cd92a08dec3b80074ca83cf2/plantuml/MSA/msa-design-patterns.puml https://gitlab.com/nghinhut/docs/blob/8e9f9814d34554d4cd92a08dec3b80074ca83cf2/plantuml/MSA/msa-design-patterns.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title Design Patterns for Microservices

!function $getBaseUrl($value = "https://gitlab.com/nghinhut/docs")
    !$CI_PROJECT_URL = %getenv("CI_PROJECT_URL")
    !if (%strlen($CI_PROJECT_URL) > 0)
        !$value = $CI_PROJECT_URL
    !endif
    !return "http://www.plantuml.com/plantuml/proxy?fmt=svg&src=" + $value + "/raw/master"
!endfunction

rectangle "Design Patterns for [[$getBaseUrl()/plantuml/msa.puml Microservices]]" as DpfMSA #yellow

rectangle "[[$getBaseUrl()/plantuml/MSA/decomposition-patterns.puml Decomposition Patterns]]" as Decomposition #green
rectangle "[[$getBaseUrl()/plantuml/MSA/integration-patterns.puml Integration Patterns]]" as Integration #green
rectangle "[[$getBaseUrl()/plantuml/MSA/database-patterns.puml Database Patterns]]" as Database #green
rectangle "[[$getBaseUrl()/plantuml/MSA/observability-patterns.puml Observability Patterns]]" as Observability #green
rectangle "[[$getBaseUrl()/plantuml/MSA/cross-cutting-concern-patterns.puml Cross-Cutting Concern Patterns]]" as CrossCuttingConcern #green
DpfMSA --- Decomposition
DpfMSA --- Integration
DpfMSA --- Database
DpfMSA --- Observability
DpfMSA --- CrossCuttingConcern
@enduml
