@startuml
title Microservices Architecture

!if (%file_exists("../shared/functions.iuml"))
    !include ../shared/functions.iuml
!else
    !include https://gitlab.com/nghinhut/docs/raw/master/plantuml/shared/functions.iuml
!endif
rectangle "<b>Microservices Architecture" as msa #green

rectangle "[[# Definition]]" as definition #yellow
rectangle "[[$getBaseUrl()/plantuml/MSA/msa-goals.puml Goals]]" as goals #yellow
rectangle "[[$getBaseUrl()/plantuml/MSA/msa-properties.puml Properties]]" as properties #yellow
rectangle "[[$getBaseUrl()/plantuml/MSA/msa-design-patterns.puml Design Patterns]]" as design_patterns #yellow

definition -- msa
goals -- msa
properties -- msa
msa -- design_patterns

@enduml
