@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F3df1026eaf1d4235a96f975a9ee7f56338654bdb%5C%2Fplantuml%5C%2FMSA%5C%2Fobservability-patterns%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/3df1026eaf1d4235a96f975a9ee7f56338654bdb/plantuml/MSA/observability-patterns.puml https://gitlab.com/nghinhut/docs/blob/3df1026eaf1d4235a96f975a9ee7f56338654bdb/plantuml/MSA/observability-patterns.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----

rectangle "Observability Patterns" as Observability #green

rectangle "Log Aggregation" as ObservabilityP1
rectangle "Performance Metrics" as ObservabilityP2
rectangle "Distributed Tracing" as ObservabilityP3
rectangle "Health Check" as ObservabilityP4
Observability --- ObservabilityP1
Observability --- ObservabilityP2
Observability --- ObservabilityP3
Observability --- ObservabilityP4
@enduml