@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F6e6cb57e2df8282c56b23193544a11451d2a5ccb%5C%2FIdM%5C%2Fdecryption%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/6e6cb57e2df8282c56b23193544a11451d2a5ccb/IdM/decryption.puml https://gitlab.com/nghinhut/docs/blob/6e6cb57e2df8282c56b23193544a11451d2a5ccb/IdM/decryption.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title IdM Decryption Function
participant "IdM Service" as idm
participant "Encryption Service" as es
participant "Security Admin" as esAdmin


idm ->> idm : decrypted1 = externalDecrypt($cipherText)
activate idm
    idm ->> es : request decrypt with $keyName='idm-key01'
    activate es
        es -> es : decrypt($algorithm, $cipherText, $masterKey)
        note right
            master key are private at Encryption Service
            only Security Admin has access.
        end note
        idm <<-- es : return decrypted string (this is decrypted1 value)
    deactivate es
deactivate idm

idm ->> idm : decrypted2 = serviceDecryption('chacha20-poly1305', $decrypted1, $serviceKey)
note left
    serviceKey is a random string secret
    generated by Service's Maintainer/Admin
    and pass though environment variable at runtime
end note
@enduml