@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F305573b699f6927e1f965f77e3012495a65d1882%5C%2FIdM%5C%2Fuc04%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/305573b699f6927e1f965f77e3012495a65d1882/IdM/uc04.puml https://gitlab.com/nghinhut/docs/blob/305573b699f6927e1f965f77e3012495a65d1882/IdM/uc04.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title ListUsers

participant "Client" as client
participant "IdM Service" as idm
participant "IdM Database" as db
participant "Encryption Service" as es

client ->> idm
activate idm

idm -> idm : encrypt()
activate idm
idm -> idm : internalEncrypt()
activate idm
deactivate idm

idm -> idm : externalEncrypt()
activate idm
idm ->> es : request encryption with alg [[https://www.vaultproject.io/docs/secrets/transit/index.html#chacha20-poly1305 ChaCha20-Poly1305 with a 256-bit key]]
note right
    POST /transit/encrypt/:name

    [[https://www.vaultproject.io/api/secret/transit/index.html#encrypt-data ref: Encrypt Data API]]
end note
activate es
idm <<-- es
deactivate es
deactivate idm
deactivate idm

idm -> db : save()
idm <-- db : result

client <<-- idm : return success response (empty body)
deactivate idm

@enduml
