@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F6e6cb57e2df8282c56b23193544a11451d2a5ccb%5C%2FIdM%5C%2Fuse-case%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/6e6cb57e2df8282c56b23193544a11451d2a5ccb/IdM/use-case.puml https://gitlab.com/nghinhut/docs/blob/6e6cb57e2df8282c56b23193544a11451d2a5ccb/IdM/use-case.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
!$BASE_URL = "http://www.plantuml.com/plantuml/proxy?fmt=svg&src=" + %getenv("CI_PROJECT_URL") + "/raw/master"
left to right direction

actor "Client" as client
actor "Encryption Service" as es
rectangle IdM {
    usecase "[[$BASE_URL/IdM/uc01.sequence.puml CreateUser()]]" as UC01
    usecase "[[$BASE_URL/IdM/uc02.sequence.puml ListUsers()]]" as UC02
    usecase "[[$BASE_URL/IdM/uc03.sequence.puml UpdateUser()]]" as UC03
    usecase "[[$BASE_URL/IdM/uc04.sequence.puml DeleteUser()]]" as UC04
}


note left of client
    Authenticated clients: Keycloak (with custom plugin),
    or any other system that has knowledge & permission to access
end note


note right of es
    supported encryption services: Vault by HashiCorp
end note


client - UC01
client - UC02
client -- UC03
client -- UC04

UC01 - es
UC02 - es
UC03 -- es
UC04 -- es

@enduml
