@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[www.nghinhut.dev?from=http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/bd040d765a886e5ad205604746534f3e7427a554/IdM/use-case.puml @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/bd040d765a886e5ad205604746534f3e7427a554/IdM/use-case.puml https://gitlab.com/nghinhut/docs/blob/bd040d765a886e5ad205604746534f3e7427a554/IdM/use-case.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----

!$REPO_URL = "https://gitlab.com/nghinhut/docs/raw/master/IdM"
!$PLANTUML_PROXY_URL = "http://www.plantuml.com/plantuml/proxy"
!$BASE_URL = $PLANTUML_PROXY_URL + "?fmt=svg&src=" + $REPO_URL
left to right direction

actor "Client" as client
actor "Encryption Service" as es
rectangle IdM {
    usecase "[[$BASE_URL/uc01.sequence.puml CreateUser()]]" as UC01
    usecase "[[$BASE_URL/uc02.sequence.puml ListUsers()]]" as UC02
    usecase "[[$BASE_URL/uc03.sequence.puml UpdateUser()]]" as UC03
    usecase "[[$BASE_URL/uc04.sequence.puml DeleteUser()]]" as UC04
}


note left of client
    Authenticated clients: Keycloak (with custom plugin),
    or any other system that has knowledge & permission to access
end note


note right of es
    supported encryption services: Vault by HashiCorp
end note


client - UC01
client - UC02
client -- UC03
client -- UC04

UC01 - es
UC02 - es
UC03 -- es
UC04 -- es


@enduml
