@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F28fac1f46a2aa25338eae0a98f95d34fa092e53d%5C%2FUMA2%5C%2Fphotos%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/28fac1f46a2aa25338eae0a98f95d34fa092e53d/UMA2/photos.puml https://gitlab.com/nghinhut/docs/blob/28fac1f46a2aa25338eae0a98f95d34fa092e53d/UMA2/photos.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title UMA2 Example: Photos application

actor "Bob" as rp
participant "Photos Webapp" as client
participant "Photos service" as rs
participant "UMA2 authorization server" as as
actor "Alice" as ro

par Get permission ticket
    client ->> rs : request access
    activate rs

    opt Invalid token or expired
        ref over rs, as : OAuth2 grant flow: Client  Credentials
    end

    ref over rs, as : Ticket request

    client <<-- rs : [UMA2] { as_uri: ...,  ticket : }
    deactivate rs
else Authentication
    ref over rp, as : OAuth2 grant flow: Authorization Code with Proof Key for Code Exchange (PKCE)
end

client ->> as : obtain permission
activate as
alt success
client <<-- as : RPT
end
deactivate as

client ->> rs : GET /photos with access token (RPT)
activate rs
ref over rs, as : Token introspection
client <<-- rs : photos
deactivate rs
@enduml