image: alpine:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy
  - release

plantuml:
  stage: build
  image: openjdk:8
  script:
    - apt-get update -qq 2>&1 >/dev/null && apt-get install -qq -y --no-install-recommends zip jq git openjdk-8-jdk graphviz 2>&1 >/dev/null
    - ./scripts/plantuml-build.sh
  artifacts:
    paths:
      - public
  only:
    changes:
      - "**/*.puml"

pages:
  stage: deploy
  image: openjdk:8
  dependencies:
    - plantuml
  script:
    - export HUGO_BASEURL=$CI_PAGES_URL
    - ./scripts/hugo-build.sh
  artifacts:
    paths:
      - public
  only:
    - master

release:
  stage: release
  image: node:10-alpine
  script:
    - apk update && apk add git
    - npm install -g semantic-release @semantic-release/gitlab
    - semantic-release -r git@gitlab.com:nghinhut/docs.git
  only:
    - master
    - schedules
