image: alpine:latest

stages:
  - build
  - deploy
  - release

plantuml-cache:
  extends: plantuml
  before_script:
    - '[[ -d public ]] && exit 0'
  only: []
  except:
    changes:
      - "**/*.puml"

plantuml:
  stage: build
  image: ubuntu:18.04
  script:
    - apt-get update -qq 2>&1 >/dev/null && apt-get install -qq -y --no-install-recommends zip jq git openjdk-8-jdk graphviz 2>&1 >/dev/null
    - ./scripts/plantuml-build.sh
  interruptible: true
  artifacts:
    paths:
      - public
  only:
    changes:
      - "**/*.puml"

pages:
  stage: deploy
  image:
    name: alpine/git:latest
    entrypoint: [""]
  dependencies:
    - plantuml
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - public
  script:
    - '[[ ! -d "public/" ]] && exit 1' # If no public/ then exit error because the site need plantuml to be compiled before deploy
    - apk add bash
#    - '[[ ! -d "public/" ]] && (set +e && wget https://gitlab.com/nghinhut/docs/-/jobs/artifacts/master/download?job=pages -O artifacts.zip; unzip artifacts.zip; rm -f artifacts.zip && set -e)'
    - export HUGO_BASEURL=$CI_PAGES_URL
    - cat ./scripts/hugo-build.sh | bash
  interruptible: true
  artifacts:
    paths:
      - public
  only:
    - master

release:
  stage: release
  image: node:10-alpine
  cache:
    paths:
      - node_modules/
  script:
    - apk update && apk add git
    - npm install -g semantic-release @semantic-release/gitlab
    - semantic-release -r git@gitlab.com:nghinhut/docs.git
  only:
    - schedules
