# Main config settings
title: NLMN
baseURL: "https://www.nghinhut.dev"
languageCode: "en-us"
copyright: "This work is licensed under a Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)"
author:
  name: "Nghi L. M. Nhựt"
  email: "nghinhut@gmail.com"
module:
  hugoVersion:
    extended: false
    min: "0.56.0"
  mounts:
    - source: web/content
      target: content
    - source: web/layouts
      target: layouts
    - source: posts
      target: content/posts
    - source: assets
      target: static/assets
    - source: web/i18n
      target: i18n
    - source: web/archetypes
      target: archetypes
    - source: _redirects
      target: static/_redirects
disableKinds:
  - taxonomy
  - taxonomyTerm
pygmentsCodeFences: true
#canonifyurls: true
outputs:
  section:
    - HTML
    - JSON
    - RSS
enableGitInfo: true

# Other configurations


