# https://github.com/gohugoio/hugo/blob/master/docs/netlify.toml
 
[build]
publish = "public"
command = "hugo --gc --minify -b $URL"
#command = "wget https://gitlab.com/nghinhut/docs/-/jobs/artifacts/master/download?job=pages -O artifacts.zip 2>&1 >/dev/null && unzip artifacts.zip 2>&1 >/dev/null && ls -la public/plantuml/ && hugo --gc --minify -b $URL"

[context.production.environment]
HUGO_VERSION = "0.59.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.59.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.59.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.59.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = "https://nghinhut.dev"

#[[redirects]]
#  from = "/plantuml/*"
#  to = "https://nghinhut.gitlab.io/docs/plantuml/:splat"
#  status = 200
#  force = true # COMMENT: ensure that we always redirect
#  headers = {X-From = "Netlify", Access-Control-Allow-Origin = "nghinhut.dev localhost"}
