@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2Fc46ad9c00ef7b2feec3a29a383ecf5c7a5e6ee35%5C%2FIdM%5C%2Fuc01%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/c46ad9c00ef7b2feec3a29a383ecf5c7a5e6ee35/IdM/uc01.puml https://gitlab.com/nghinhut/docs/blob/c46ad9c00ef7b2feec3a29a383ecf5c7a5e6ee35/IdM/uc01.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----

!$BASE_URL = "http://www.plantuml.com/plantuml/proxy?fmt=svg&src=" + %getenv("CI_PROJECT_URL") + "/raw/master"
title Create A New User (UMA2 Protected)
!pragma teoz true

participant "Client" as client
participant "IdM Service" as idm
participant "IdM Database" as db
participant "UMA2 Authorization Server" as as
participant "Encryption Service" as es

activate client
client ->> idm : client request permission ticket
activate idm
    idm -> idm : createPermissionTicket()
    activate idm
        opt invalid or expired access token (PAT)
            ref over idm, as
                OAuth2 Client Credentials Grant
            end
        end
        idm ->> as : create permission ticket with resource scopes: [ 'create-user' ]
        activate as
        deactivate as
        idm <<-- as
    deactivate idm

client <<-- idm : 200 response { as_uri: ..., ticket: ... }
deactivate idm

{start_d1} client ->> idm : request create new user with access token (RPT)
activate idm


idm -> idm : tokenIntrospect()
activate idm
    opt for additional validation\n(offer better security but increases request duration
        ref over idm, as
            Introspect token with Authz Server
        end
    end
deactivate idm


idm -> idm : policyEnforce()
activate idm
deactivate idm


loop for each attribute in user's attributes
    ref over idm, es
        Encrypt user's attribute by [[$BASE_URL/IdM/encryption.function.puml Encryption($attribute)]]
    end
end


idm -> db : save()
    db -> db : INSERT ... INTO "[[$BASE_URL/IdM/class.puml Users]]";
idm <-- db : result

{end_d1} client <<-- idm : return success response (empty body)
deactivate client

== Create Blind Indexing ==
idm -> idm : createBlindIndex()
activate idm
    loop for each attribute in ['username', 'email', 'first_name', 'last_name']
        idm -> idm : hash_hmac('sha256', $attribute, $masterKey)
    end
    idm -> db : updateBlindIndex()
        db -> db : INSERT ... INTO "[[$BASE_URL/IdM/class.puml UsersFilters]]"
    idm <<-- db
deactivate idm
deactivate idm


'Duration Constrains
{start_d1} <-> {end_d1} : <5s
@enduml
