@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[www.nghinhut.dev?from=http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/bd040d765a886e5ad205604746534f3e7427a554/VDAT/vdat.puml @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/bd040d765a886e5ad205604746534f3e7427a554/VDAT/vdat.puml https://gitlab.com/nghinhut/docs/blob/bd040d765a886e5ad205604746534f3e7427a554/VDAT/vdat.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----

package "IAM" {
    component "Authz Server" as as
    component Vault as vault
    component IdP as idp

'    interface "OAuth2 Authentication" as IOAuth2Authentication
'    interface "UMA2 Authorization" as IUMA2Authorization
'    as -- IOAuth2Authentication
'    as -- IUMA2Authorization
    interface "Encryption" as IEncrypt
    interface "User" as IUser
}

package "Sharing" {
    component "Health Record Service" as record
    interface "Health Record" as IHealthRecord
    component "HAPI FHIR Gateway" as fhir
    interface "FHIR (HEART)" as IFHIR
}

package "Data Collection Management" {
    component "Collector Service" as collector
    component "SMS Service" as sms
    component "Gatekeeper" as collector_gatekeeper
    interface "Data Collection Management" as IDataCollectionManagement
    interface "Secure Data Collection Management" as ISecureDataCollectionManagement
}






vault - IEncrypt
IEncrypt <. idp : use
idp -- IUser
IUser <. as : use
IUser <... fhir : use


record - IHealthRecord
IHealthRecord <. fhir : use
fhir - IFHIR
IHealthRecord <.... collector : use


collector - IDataCollectionManagement
IDataCollectionManagement <. collector_gatekeeper : use
collector_gatekeeper - ISecureDataCollectionManagement

IDataCollectionManagement <.. sms : use

@enduml
