!function $getBaseUrl($value = "https://gitlab.com/nghinhut/docs")
    !$CI_PROJECT_URL = %getenv("CI_PROJECT_URL")
    !if (%strlen($CI_PROJECT_URL) > 0)
        !$value = $CI_PROJECT_URL
    !endif

'    !return "http://www.plantuml.com/plantuml/proxy?fmt=svg&src=" + $value + "/raw/master"

    !return $value
!endfunction
