!function $getBaseUrl($value = "https://gitlab.com/nghinhut/docs")
    !$CI_PROJECT_URL = %getenv("CI_PROJECT_URL")
    !if (%strlen($CI_PROJECT_URL) > 0)
        !$value = $CI_PROJECT_URL
    !endif
    !return $value
!endfunction
