@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F225d1c25d8dd9d23033cf4ff7cccac23f934538b%5C%2Fplantuml%5C%2FVDAT%5C%2Freset-password-with-otp%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/225d1c25d8dd9d23033cf4ff7cccac23f934538b/plantuml/VDAT/reset-password-with-otp.puml https://gitlab.com/nghinhut/docs/blob/225d1c25d8dd9d23033cf4ff7cccac23f934538b/plantuml/VDAT/reset-password-with-otp.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title Reset Password with OTP

actor "unauthenticated user" as rp
participant "OTP Reset Password Web UI" as client
participant "OTP Reset Password Service" as rs
participant "Identity Provider " as idp
participant "SMS Service " as sms
participant "Email Service " as email
participant "reCAPTCHA " as rc

rp --> client : request reset password with\nusername = "user@vdatlab.com"
activate client
client -> rs : request reset password with\nusername,\nmethod: sms | email,\ncode_verifier,\nreCAPTCHA token
activate rs
rs -> rc : verify reCAPTCHA token
rs <<-- rc : result
alt invalid token
client <<-- rs : 400: Prompt: Invalid token
else valid token
rs -> idp : check user exists
rs <<-- idp : result

alt user exists & user.otp_password_reset_disable != true
    rs -> rs : getUserInfo()
    rs -> rs : create reset password code (Ex: asdvasvabfthtadsfasdv)
    rs -> rs : generate otp for sessionId
    alt send OTP via SMS
        rs ->> sms : request send otp code to user's phone
        rs <<-- sms : result
    else send OTP via Email
        rs ->> email : request send OTP code to user's email
        rs <<-- email : result
    end
    alt request send OTP accepted
        client <<-- rs : 200\n{ code: "asdvasvabfthtadsfasdv",\nemail: u**r@vdatlab.com,\nphone: 09****23}
    else else
        client <<-- rs : 503 Service Unavailable
    end
else user not found
    client <<-- rs : 404
end
deactivate rs

alt request success
    rp <- client : prompt: Success message,\nredirect user to OTP submit form
else else
    rp <-- client : Prompt: Error message
end

rp -> client : new password + enter otp
client ->> rs : request reset password\nwith password, OTP, code, challenge
activate rs
    rs -> rs : SELECT * FROM users\nWHERE\n\t\tcode=$code\n\tAND otp=$otp\n\tAND code_verifier=hash(SHA256, code);
    alt user found
        rs -> idp : reset user password to "...."
        rs <-- idp : result
        client <<-- rs : 204
    else else
        client <<-- rs : 403
    end
deactivate rs

deactivate client
end
@enduml
