@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F9afacf787796dfb7c1260b818c0c61e3649fc73f%5C%2Fplantuml%5C%2FVDAT%5C%2Fvdat%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/9afacf787796dfb7c1260b818c0c61e3649fc73f/plantuml/VDAT/vdat.puml https://gitlab.com/nghinhut/docs/blob/9afacf787796dfb7c1260b818c0c61e3649fc73f/plantuml/VDAT/vdat.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----

package "IAM" {
    component "Authz Server" as as
    component Vault as vault
    component IdP as idp

'    interface "OAuth2 Authentication" as IOAuth2Authentication
'    interface "UMA2 Authorization" as IUMA2Authorization
'    as -- IOAuth2Authentication
'    as -- IUMA2Authorization
    interface "Encryption" as IEncrypt
    interface "User" as IUser
}

package "Sharing" {
    component "Health Record Service" as record
    interface "Health Record" as IHealthRecord
    component "HAPI FHIR Gateway" as fhir
    interface "FHIR (HEART)" as IFHIR
}

package "Data Collection Management" {
    component "Collector Service" as collector
    component "SMS Service" as sms
    component "Gatekeeper" as collector_gatekeeper
    interface "Data Collection Management" as IDataCollectionManagement
    interface "Secure Data Collection Management" as ISecureDataCollectionManagement
}






vault - IEncrypt
IEncrypt <. idp : use
idp -- IUser
IUser <. as : use
IUser <... fhir : use


record - IHealthRecord
IHealthRecord <. fhir : use
fhir - IFHIR
IHealthRecord <.... collector : use


collector - IDataCollectionManagement
IDataCollectionManagement <. collector_gatekeeper : use
collector_gatekeeper - ISecureDataCollectionManagement

IDataCollectionManagement <.. sms : use
@enduml