@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F125ff57f05f4260e72c6ca8346868dc5a679be2f%5C%2FMSA%5C%2Fdecomposition-patterns%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/125ff57f05f4260e72c6ca8346868dc5a679be2f/MSA/decomposition-patterns.puml https://gitlab.com/nghinhut/docs/blob/125ff57f05f4260e72c6ca8346868dc5a679be2f/MSA/decomposition-patterns.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----

rectangle "Decomposition Patterns" as Decomposition #green

rectangle "Decompose by Business Capability" as DecompositionP1
rectangle "Decompose by Sub-domain" as DecompositionP2
rectangle "Decompose by Transactions\n/ Two-phase commit (2pc) pattern" as DecompositionP3
rectangle "Strangler Pattern" as DecompositionP4
rectangle "Bulkhead Pattern" as DecompositionP5
rectangle "Sidecar Pattern" as DecompositionP6
Decomposition --- DecompositionP1
Decomposition --- DecompositionP2
Decomposition --- DecompositionP3
Decomposition --- DecompositionP4
Decomposition --- DecompositionP5
Decomposition --- DecompositionP6
@enduml
