@startuml
'-----BEGIN HEADER-----
'-----END HEADER-----

rectangle "Decomposition Patterns" as Decomposition #green

rectangle "Decompose by Business Capability" as DecompositionP1
rectangle "Decompose by Sub-domain" as DecompositionP2
rectangle "Decompose by Transactions\n/ Two-phase commit (2pc) pattern" as DecompositionP3
rectangle "Strangler Pattern" as DecompositionP4
rectangle "Bulkhead Pattern" as DecompositionP5
rectangle "Sidecar Pattern" as DecompositionP6
Decomposition --- DecompositionP1
Decomposition --- DecompositionP2
Decomposition --- DecompositionP3
Decomposition --- DecompositionP4
Decomposition --- DecompositionP5
Decomposition --- DecompositionP6
@enduml
