@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[www.nghinhut.dev?from=http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/bd040d765a886e5ad205604746534f3e7427a554/MSA/msa-properties.puml @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/bd040d765a886e5ad205604746534f3e7427a554/MSA/msa-properties.puml https://gitlab.com/nghinhut/docs/blob/bd040d765a886e5ad205604746534f3e7427a554/MSA/msa-properties.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title Microservices Architecture Built-in Properties

rectangle "Microservices" as msa

circle "Scalability" as scalability
circle "Availability" as availability
circle "Resiliency" as resiliency
circle "Flexibility" as flexibility
circle "Independent, autonomous" as independent_autonomous
circle "Decentralized governance" as decentralized_governance
circle "Failure isolation" as failure_isolation
circle "Auto-Provisioning" as auto_provisioning
circle "Continuous delivery through DevOps" as cd

scalability -- msa
availability -- msa
resiliency -- msa
flexibility -- msa
msa -- independent_autonomous
msa -- decentralized_governance
msa -- failure_isolation
msa -- auto_provisioning
msa -- cd

@enduml
