@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[mailto:nghinhut@gmail.com @nghinhut]]
footer [[https://gitlab.com/nghinhut/docs/blob/4c293fca2537a296caa852c72169430d55b4d64f/MSA/msa-goals.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title The Microservices Goals

rectangle "Microservices Architecture" as msa #green

rectangle "Reduce Cost" as goal1 #yellow
rectangle "Increase Release Speed" as goal2 #yellow
rectangle "Improve Resilience" as goal3 #yellow
rectangle "Enable Visibility" as goal4 #yellow

msa -- goal1
msa -- goal2
msa -- goal3
msa -- goal4



@enduml
