@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[www.nghinhut.dev?from=http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/bd040d765a886e5ad205604746534f3e7427a554/MSA/msa-goals.puml @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/bd040d765a886e5ad205604746534f3e7427a554/MSA/msa-goals.puml https://gitlab.com/nghinhut/docs/blob/bd040d765a886e5ad205604746534f3e7427a554/MSA/msa-goals.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title The Microservices Goals

rectangle "Microservices Architecture" as msa #green

rectangle "Reduce Cost" as goal1 #yellow
rectangle "Increase Release Speed" as goal2 #yellow
rectangle "Improve Resilience" as goal3 #yellow
rectangle "Enable Visibility" as goal4 #yellow

msa -- goal1
msa -- goal2
msa -- goal3
msa -- goal4



@enduml
