@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F7b6958bedf5dc42d3f2320c7c34daf4d71556d92%5C%2FMSA%5C%2Fmsa-properties%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/7b6958bedf5dc42d3f2320c7c34daf4d71556d92/MSA/msa-properties.puml https://gitlab.com/nghinhut/docs/blob/7b6958bedf5dc42d3f2320c7c34daf4d71556d92/MSA/msa-properties.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title Microservices Architecture Built-in Properties

rectangle "Microservices" as msa

circle "Scalability" as scalability
circle "Availability" as availability
circle "Resiliency" as resiliency
circle "Flexibility" as flexibility
circle "Independent, autonomous" as independent_autonomous
circle "Decentralized governance" as decentralized_governance
circle "Failure isolation" as failure_isolation
circle "Auto-Provisioning" as auto_provisioning
circle "Continuous delivery through DevOps" as cd

scalability -- msa
availability -- msa
resiliency -- msa
flexibility -- msa
msa -- independent_autonomous
msa -- decentralized_governance
msa -- failure_isolation
msa -- auto_provisioning
msa -- cd

@enduml