@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[www.nghinhut.dev?from=https%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fblob%5C%2F6a4ac3f542c9f124b6ab5e7932d4e491ca7654ff%5C%2FMSA%5C%2Fmsa-goals%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/6a4ac3f542c9f124b6ab5e7932d4e491ca7654ff/MSA/msa-goals.puml https://gitlab.com/nghinhut/docs/blob/6a4ac3f542c9f124b6ab5e7932d4e491ca7654ff/MSA/msa-goals.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title The Microservices Goals

rectangle "Microservices Architecture" as msa #green

rectangle "Reduce Cost" as goal1 #yellow
rectangle "Increase Release Speed" as goal2 #yellow
rectangle "Improve Resilience" as goal3 #yellow
rectangle "Enable Visibility" as goal4 #yellow

msa -- goal1
msa -- goal2
msa -- goal3
msa -- goal4



@enduml
