@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[www.nghinhut.dev?from=http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/bd040d765a886e5ad205604746534f3e7427a554/MSA/msa.puml @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/bd040d765a886e5ad205604746534f3e7427a554/MSA/msa.puml https://gitlab.com/nghinhut/docs/blob/bd040d765a886e5ad205604746534f3e7427a554/MSA/msa.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title Microservices Architecture

!$REPO_URL = "https://gitlab.com/nghinhut/docs/raw/master/MSA"
!$PLANTUML_PROXY_URL = "http://www.plantuml.com/plantuml/proxy"
!$BASE_URL = $PLANTUML_PROXY_URL + "?fmt=svg&src=" + $REPO_URL

rectangle "<b>Microservices Architecture" as msa #green

rectangle "[[# Definition]]" as definition #yellow
rectangle "[[$BASE_URL/msa-goals.puml Goals]]" as goals #yellow
rectangle "[[$BASE_URL/msa-properties.puml Properties]]" as properties #yellow
rectangle "[[$BASE_URL/msa-design-patterns.puml Design Patterns]]" as design_patterns #yellow

definition -- msa
goals -- msa
properties -- msa
msa -- design_patterns

@enduml
