@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[mailto:nghinhut@gmail.com @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/4725f15bbff59f2227e3834e02e5dd3b17c9d433/MSA/observability-patterns.puml https://gitlab.com/nghinhut/docs/blob/4725f15bbff59f2227e3834e02e5dd3b17c9d433/MSA/observability-patterns.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----

rectangle "Observability Patterns" as Observability #green

rectangle "Log Aggregation" as ObservabilityP1
rectangle "Performance Metrics" as ObservabilityP2
rectangle "Distributed Tracing" as ObservabilityP3
rectangle "Health Check" as ObservabilityP4
Observability --- ObservabilityP1
Observability --- ObservabilityP2
Observability --- ObservabilityP3
Observability --- ObservabilityP4
@enduml
