@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header @nghinhut
footer https://gitlab.com/nghinhut/docs/raw/9688f34d89be35b55ae664523133555104b4bd3b/MSA/observability-patterns.puml
'-----END auto generated metadata please keep comment here to allow auto update-----

rectangle "Observability Patterns" as Observability #green

rectangle "Log Aggregation" as ObservabilityP1
rectangle "Performance Metrics" as ObservabilityP2
rectangle "Distributed Tracing" as ObservabilityP3
rectangle "Health Check" as ObservabilityP4
Observability --- ObservabilityP1
Observability --- ObservabilityP2
Observability --- ObservabilityP3
Observability --- ObservabilityP4
@enduml
