@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F91eef9cc31203c36737a9ca317b8e3a138a2653e%5C%2Fplantuml%5C%2FUMA2%5C%2Ftoken-introspection%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/91eef9cc31203c36737a9ca317b8e3a138a2653e/plantuml/UMA2/token-introspection.puml https://gitlab.com/nghinhut/docs/blob/91eef9cc31203c36737a9ca317b8e3a138a2653e/plantuml/UMA2/token-introspection.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title UMA2 Token Introspection

participant "client" as client
participant "resource server" as rs
participant "authorization server " as as

activate client
client ->> rs : Request resource with access token (RPT)
activate rs

== Token Introspection ==
alt using JWT public key
    rs -> rs : jwt.verify($token)
    note right
        {
           "active":true,
           "exp":1256953732,
           "iat":1256912345,
           "permissions":[
              {
                 "resource_id":"112210f47de98100",
                 "resource_scopes":[
                    "view",
                    "http://photoz.example.com/dev/actions/print"
                 ],
                 "exp":1256953732
              }
           ]
        }
    end note
else using PROTECTION API: Introspection endpoint
    rs ->> as : introspect RPT
    note left
        POST /introspect HTTP/1.1
        Host: as.example.com
        Authorization: Bearer 204c69636b6c69
        ...
        token=sbjsbhs(/SSJHBSUSSJHVhjsgvhsgvshgsv
        }
    end note
    activate as
    rs <<-- as : return object
    note right
        HTTP/1.1 200 OK
        Content-Type: application/json
        Cache-Control: no-store
        ...

        {
           "active":true,
           "exp":1256953732,
           "iat":1256912345,
           "permissions":[
              {
                 "resource_id":"112210f47de98100",
                 "resource_scopes":[
                    "view",
                    "http://photoz.example.com/dev/actions/print"
                 ],
                 "exp":1256953732
              }
           ]
        }
    end note
    deactivate as
end

== Access Control ==

ref over rs
    Access Control
end

alt access granted
    client <<-- rs : Protected resource
else access denied
    client <<-- rs : permission denied response with permission ticket
end
deactivate rs
deactivate client
@enduml