baseURL: "https://www.nghinhut.dev"
author:
  name: "Nghi L. M. Nhựt"
  email: "nghinhut@gmail.com"
module:
  hugoVersion:
    extended: false
    min: "0.55.0"
disableKinds:
  - taxonomy
  - taxonomyTerm
pygmentsCodeFences: true
canonifyurls: true
outputs:
  section:
    - HTML
    - JSON
