@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F3df1026eaf1d4235a96f975a9ee7f56338654bdb%5C%2Fplantuml%5C%2FIdM%5C%2Fclass%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/3df1026eaf1d4235a96f975a9ee7f56338654bdb/plantuml/IdM/class.puml https://gitlab.com/nghinhut/docs/blob/3df1026eaf1d4235a96f975a9ee7f56338654bdb/plantuml/IdM/class.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title IdM Classes

class "User" as user {
    -- private --
    - id: string
    - createdAt: timestamp
    - updatedAt: timestamp
    -- encrypted --
    - username: string
    - email: string
    - firstName: string
    - lastName: string
    - attributes: {key: string, value: Object}[]
    .. Getter ..
    + getId() : string
    + getUsername() : string
    + getEmail() : string
    + getFirstName() : string
    + getLastName() : string
    + getAttribute(key: string) : Object
    + getAttributes() : <string, Object>
    .. Setter ..
    + setUsername(username: string) : void
    + setEmail(email: string) : void
    + setFirstName(firstName: string) : void
    + setLastName(lastName: string) : void
    + setAttribute(key: string, value: Object) : void
}

class "UserFilter" as user_filter {
    -- private --
    - id: number
    - UserId: string
    -- encrypted --
    - label: string
    - value: string
    .. Getter ..
    + getId() : number
    + getUserId() : string
    + getLabel() : string
    + getValue() : string
    .. Setter ..
    + setUserId(userId: string) : void
    + setLabel(label: string) : void
    + setValue(value: string) : void
}

user -* user_filter : hasMany

@enduml
