@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F3df1026eaf1d4235a96f975a9ee7f56338654bdb%5C%2Fplantuml%5C%2FIdM%5C%2Fcreate-permission-ticket%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/3df1026eaf1d4235a96f975a9ee7f56338654bdb/plantuml/IdM/create-permission-ticket.puml https://gitlab.com/nghinhut/docs/blob/3df1026eaf1d4235a96f975a9ee7f56338654bdb/plantuml/IdM/create-permission-ticket.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title Create Permission Ticket

participant "Client" as client
participant "IdM Service" as idm
participant "UMA2 Authorization Server" as as

client ->> idm : client request permission ticket
activate idm
    idm -> idm : createPermissionTicket()
    activate idm
        opt invalid or expired access token (PAT)
            ref over idm, as
                OAuth2 Client Credentials Grant
            end
        end
        idm ->> as : create permission ticket with resource scopes
        note left
            POST /<permission_endpoint> HTTP/1.1
            Host: as.example.com
            Authorization: Bearer $PAT
            . . .
            [{
                "resource_id": "$resourceId",
                "resource_scopes": [ "view" ]
            }]
        end note
        activate as
        idm <<-- as
        deactivate as
    deactivate idm
    client <<-- idm : 200 response { as_uri: ..., ticket: ... }
deactivate idm
@enduml
