@startuml
title Create Permission Ticket

participant "Client" as client
participant "IdM Service" as idm
participant "UMA2 Authorization Server" as as

client ->> idm : client request permission ticket
activate idm
    idm -> idm : createPermissionTicket()
    activate idm
        opt invalid or expired access token (PAT)
            ref over idm, as
                OAuth2 Client Credentials Grant
            end
        end
        idm ->> as : create permission ticket with resource scopes
        note left
            POST /<permission_endpoint> HTTP/1.1
            Host: as.example.com
            Authorization: Bearer $PAT
            . . .
            [{
                "resource_id": "$resourceId",
                "resource_scopes": [ "view" ]
            }]
        end note
        activate as
        idm <<-- as
        deactivate as
    deactivate idm
    client <<-- idm : 200 response { as_uri: ..., ticket: ... }
deactivate idm
@enduml
