@startuml
'-----START auto generated metadata please keep comment here to allow auto update-----
'-----DON'T EDIT THIS SECTION, INSTEAD RE-RUN prebuild.sh TO UPDATE-----
header [[https://www.nghinhut.dev?from=http%5C%3A%5C%2F%5C%2Fwww%5C.plantuml%5C.com%5C%2Fplantuml%5C%2Fproxy%3Ffmt%3Dsvg%5C%26src%3Dhttps%5C%3A%5C%2F%5C%2Fgitlab%5C.com%5C%2Fnghinhut%5C%2Fdocs%5C%2Fraw%5C%2F2e9fc30c66c1d3614c85e0e8f6b5a0a12f8726df%5C%2Fplantuml%5C%2FIdM%5C%2Fquery-encrypted-users%5C.puml%0A @nghinhut]]
footer [[http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://gitlab.com/nghinhut/docs/raw/2e9fc30c66c1d3614c85e0e8f6b5a0a12f8726df/plantuml/IdM/query-encrypted-users.puml https://gitlab.com/nghinhut/docs/blob/2e9fc30c66c1d3614c85e0e8f6b5a0a12f8726df/plantuml/IdM/query-encrypted-users.puml]]
'-----END auto generated metadata please keep comment here to allow auto update-----
title Query Encrypted Users

participant "IdM Service" as idm
participant "IdM Database" as db

idm -> idm : queryUsers()
activate idm
    idm -> db : SELECT * FROM UserFilters WHERE label="username" AND value=hash_hmac('sha256', $username, $masterKey) GROUP BY id
    idm <-- db : results

    loop for each result in results
        idm -> db : SELECT * FROM Users WHERE id = result.UserId
        idm <-- db : user <//encrypted//>
    end
deactivate idm
@enduml