@startuml
title List Users Stream

!if (%file_exists("../shared/functions.iuml"))
    !include ../shared/functions.iuml
!else
    !include https://nghinhut.gitlab.io/docs/plantuml/shared/functions.iuml
!endif

participant "Client" as client
participant "IdM Service" as idm
participant "IdM Database" as db
participant "UMA2 Authorization Server" as as
participant "Encryption Service" as es

ref over client, idm, as
    [[$getBaseUrl()/plantuml/IdM/create-permission-ticket.function.puml{} Create Permission Ticket]] with resources scopes = [ 'list-users' ]
end

client ->> idm : list users
activate idm
    ref over idm
        [[$getBaseUrl()/plantuml/IdM/query-encrypted-users.function.puml Query Encrypted Users]] with empty query
    end

    loop for each user in users <//encrypted//>
        idm -> idm : userMsg = new idmGrpc.User()     // proto message
        loop for each attribute in user's attributes
            ref over idm, es
                Decrypt user's attribute by [[$getBaseUrl()/plantuml/IdM/decryption.function.puml{} Decryption(attribute)]]
            end

            idm -> idm : userMsg.set(attribute //<decrypted>//, value)
        end

        client <<-- idm : write userMsg
    end

deactivate idm
@enduml
